version: '3.3'

services:
  mysql-svc:
    image: mysql:8.0.28
    container_name: mysql
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}    
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: noob
    networks:
      - otserver
    ports:
      - 3306:3306
    volumes:
        - ${PWD}/sql/:/docker-entrypoint-initdb.d/

  phpmyadmin-svc:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      mysql-svc:
        condition: service_started
    environment:
      PMA_HOST: mysql-svc
      PMA_PORT: 3306
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}      
    networks:
      - otserver
    ports:
      - 9090:80

  php-svc:
    image: php:8.0-apache
    container_name: php
    depends_on:
      mysql-svc:
        condition: service_started
    environment:
      DOCKER_NETWORK_GATEWAY_ENV: ${DOCKER_NETWORK_GATEWAY}
      SERVER_NAME_ENV: ${SERVER_NAME}
      DATABASE_NAME_ENV: ${DATABASE_NAME}
      DATABASE_USER_ENV: ${DATABASE_USER}
      DATABASE_PASSWORD_ENV: ${DATABASE_PASSWORD}
    networks:
      - otserver
    ports:
      - 8080:80
    volumes:
      - ${PWD}/site/:/var/www/html
      - ${PWD}/server/:/home/server     # mapeamento necessario se for configurar Gesior2012 ou myAAC

  server-svc:
    image: ubuntu:22.04
    container_name: server
    depends_on:
      mysql-svc:
        condition: service_started
    restart: on-failure
    working_dir: /server
    entrypoint: |
      /bin/bash -c "
        apt update && \
        apt install libgomp1 && \
        ./canary
      "
    environment:
      DOCKER_NETWORK_GATEWAY_ENV: ${DOCKER_NETWORK_GATEWAY}
      SERVER_NAME_ENV: ${SERVER_NAME}
      DATABASE_NAME_ENV: ${DATABASE_NAME}
      DATABASE_USER_ENV: ${DATABASE_USER}
      DATABASE_PASSWORD_ENV: ${DATABASE_PASSWORD}      
    networks:
      - otserver
    ports:
      - 7171:7171
      - 7172:7172      
    volumes:
        - ${PWD}/server:/server

networks:
  otserver:
    driver: bridge
    ipam:
     config:
       - subnet: ${DOCKER_NETWORK_CIDR}
         gateway: ${DOCKER_NETWORK_GATEWAY}
